# -*- coding: utf-8 -*-
"""Studying COVID-19.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xKbcNJozE7jGR3MB-raeKZbCWuJA0fWE

# Studying COVID-19

### Setup

Let's setup Spark Colab environment.  Run the cell below!
"""

!pip install pyspark
!pip install -U -q PyDrive
!apt install openjdk-8-jdk-headless -qq
import os
os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-8-openjdk-amd64"

"""Authenticating a Google Drive client to download the files we will be process on Spark job."""

from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials

# Authenticate and create the PyDrive client
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

id='1YT7ttUAafCjbVdm6obeHp1TWAK0rEtoR'
downloaded = drive.CreateFile({'id': id})
downloaded.GetContentFile('time_series_covid19_confirmed_global.csv')

id='1YxEA5UQ2EFJ_9oLssM__Gs1ncVNufGNA'
downloaded = drive.CreateFile({'id': id})
downloaded.GetContentFile('time_series_covid19_deaths_global.csv')

id='1CNxszuZTeIw-5cF5yrzKMZdb1qV0hSoy'
downloaded = drive.CreateFile({'id': id})
downloaded.GetContentFile('time_series_covid19_recovered_global.csv')

"""If you executed the cells above, you should be able to see the dataset I will be using for this Colab under the "Files" tab on the left panel.

Next, Let's import some of the common libraries needed for our task.
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
# %matplotlib inline

import pyspark
from pyspark.sql import *
from pyspark.sql.types import *
from pyspark.sql.functions import *
from pyspark import SparkContext, SparkConf

"""Let's initialize the Spark context."""

sc.stop()

# create the session
conf = SparkConf().set("spark.ui.port", "4050")

# create the context
sc = pyspark.SparkContext(conf=conf)
spark = SparkSession.builder.getOrCreate()

"""You can easily check the current version and get the link of the web interface. In the Spark UI, you can monitor the progress of your job and debug the performance bottlenecks (if your Colab is running with a **local runtime**)."""

spark

"""If you are running this Colab on the Google hosted runtime, the cell below will create a *ngrok* tunnel which will allow you to still check the Spark UI."""

!wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
!unzip ngrok-stable-linux-amd64.zip
get_ipython().system_raw('./ngrok http 4050 &')
!curl -s http://localhost:4040/api/tunnels | python3 -c \
    "import sys, json; print(json.load(sys.stdin)['tunnels'][0]['public_url'])"

"""### Data Loading

In this Notebook, I will be analyzing the timeseries data of the Coronavirus COVID-19 Global Cases, collected by Johns Hopkins CSSE.

Here you can check a realtime dashboard based on this dataset: [https://www.arcgis.com/apps/opsdashboard/index.html?fbclid=IwAR2hQKsEZ3D38wVtXGryUhP9CG0Z6MYbUM_boPEaV8FBe71wUvDPc65ZG78#/bda7594740fd40299423467b48e9ecf6](https://www.arcgis.com/apps/opsdashboard/index.html?fbclid=IwAR2hQKsEZ3D38wVtXGryUhP9CG0Z6MYbUM_boPEaV8FBe71wUvDPc65ZG78#/bda7594740fd40299423467b48e9ecf6)

---



*   ```confirmed```: dataframe containing the cumulative number of confirmed COVID-19 cases, divided by geographical area
*   ```deaths```: dataframe containing the cumulative number of deaths due to COVID-19, divided by geographical area
*   ```recovered```: dataframe containing the cumulative number of recoevered patients, divided by geographical area

The data sets contain data entries for each day, representing the cumulative totals as of that day.
"""

confirmed = spark.read.csv('time_series_covid19_confirmed_global.csv', header=True)
deaths = spark.read.csv('time_series_covid19_deaths_global.csv', header=True)
recovered = spark.read.csv('time_series_covid19_recovered_global.csv', header=True)

confirmed.printSchema()

def md5(s):
  import hashlib
  m = hashlib.md5()
  m.update(s.encode())
  return m.hexdigest()[:2]

md5('3/5/20')
confirmed.show()

"""### Analyzing COVID-19 timeseries data

Consider the entries for May 1, 2021, in the timeseries, and compute:


*   number of confirmed COVID-19 cases across the globe
*   number of deaths due to COVID-19 (across the globe)
*   number of recovered patients across the globe
"""

def list_sum(l):
  sum = 0
  for x in l:
    sum += int(x)
  return sum
confirmed_list = confirmed.select('3/5/20').rdd.flatMap(lambda x: x).collect()
deaths_list = deaths.select('3/5/20').rdd.flatMap(lambda x: x).collect()
recovered_list = recovered.select('3/5/20').rdd.flatMap(lambda x: x).collect()

print("number of confirmed COVID-19 cases across the globe is: {}".format(list_sum(confirmed_list)))
print("number of deaths due to COVID-19 cases across the globe is: {}".format(list_sum(deaths_list)))
print("number of recovered patients across the globe is: {}".format(list_sum(recovered_list)))

"""Consider only the most recent data points for March 1, 2020, and March 1, 2021 in the timeseries, and filter out the geographical locations where less than 50 cases have been confirmed. For the areas still taken into consideration after the filtering step, compute the ratio between number of recovered patients and number of confirmed cases."""

confirmed_list = confirmed.select('Province/State', 'Country/Region', col('3/5/20').alias('confirmed'))
deaths_list = deaths.select('Province/State', 'Country/Region', col('3/5/20').alias('deaths'))
recovered_list = recovered.select('Province/State', 'Country/Region', col('3/5/20').alias('recovered'))
result = confirmed_list.join(deaths_list, ['Province/State', 'Country/Region'])
result = result.join(recovered_list, ['Province/State', 'Country/Region'])
result = result.withColumn("%recovered", result.recovered / result.confirmed)
result = result.withColumn("%deaths", result.deaths / result.confirmed)

"""Following the same filtering strategy as above, I am now computing the ratio between number of deaths and number of confirmed cases."""

result = result.filter(result.confirmed >= 50).sort("%recovered", ascending = False)
result.show()

result = result.filter(result.confirmed >= 50).sort("%deaths", ascending = False)
result.show()